package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// scanFlagList is the single source of truth for shell completions: every
// flag parseScanArgs understands. Keep it in sync when adding flags.
var scanFlagList = []string{
	"--json", "--api", "--stealth", "--threads", "--rate-limit", "--verbose",
	"--min-severity", "--enumerate", "--max-requests", "--output", "--silent",
	"--user-agent", "--random-user-agent", "--detection-mode", "--proxy",
	"--proxy-auth", "--proxy-target-only", "--tls-fingerprint",
	"--per-host-rate-limit", "--no-xmlrpc", "--checks", "--timeout",
	"--content-dir", "--plugins-dir", "--exclude-content-based", "--scope",
	"--no-update-check", "--no-update", "--plugins-list", "--themes-list",
	"--max-scan-duration", "--cache-ttl", "--stream", "--config", "--nuclei",
	"--nuclei-template-dir", "--nuclei-args", "--poc-tracker-dir", "--no-pocs",
	"--passwords", "--usernames", "--user", "--xmlrpc-brute",
	"--multicall-max-passwords", "--wp-auth", "--no-brute", "--no-summary",
	"--strict-wp", "--crawl-pages", "--fail-on", "--no-intel",
	"--fingerprint-db", "--no-popular", "--allow-foreign-redirect",
	"--retries", "--jobs", "--no-discover-404", "--fail-on-rate-limited",
	"--nuclei-min-severity", "--outputs", "--wp-version", "--disable-tls-checks",
	"--update-db",
	"--targets", "--profile", "--connect-timeout", "--request-timeout",
	"--format", "--db",
	"--basic-auth", "--cookie", "--headers", "--vhost", "--force",
	"--exclude-vulns",
}

var onyxSubcommands = []string{"scan", "update", "version", "db", "cache", "watch", "doctor", "diff", "example-config", "completion"}
var dbSubcommands = []string{"stats", "lookup", "top", "search", "diff"}
var cacheSubcommands = []string{"stats", "purge"}

func runCompletion(args []string) int {
	if len(args) != 1 {
		fmt.Fprintln(os.Stderr, "usage: onyx completion bash|zsh|fish")
		return 2
	}
	flags := append([]string{}, scanFlagList...)
	sort.Strings(flags)
	var b strings.Builder
	switch args[0] {
	case "bash":
		writeBashCompletion(&b, flags)
	case "zsh":
		writeZshCompletion(&b, flags)
	case "fish":
		writeFishCompletion(&b, flags)
	default:
		fmt.Fprintf(os.Stderr, "unknown shell %q (use bash, zsh or fish)\n", args[0])
		return 2
	}
	_, _ = os.Stdout.WriteString(b.String())
	return 0
}

func writeBashCompletion(b *strings.Builder, flags []string) {
	b.WriteString(`# bash completion for onyx (generated by 'onyx completion bash')
_onyx_completions() {
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local i sub=""
  for ((i=1; i < COMP_CWORD; i++)); do
    case "${COMP_WORDS[i]}" in
      scan|update|version|db|cache|watch|completion) sub="${COMP_WORDS[i]}" ;;
    esac
  done
  if [[ -z "$sub" ]]; then
    COMPREPLY=( $(compgen -W "scan update version db cache watch completion" -- "$cur") )
    return
  fi
  if [[ "$sub" == "db" ]]; then
    COMPREPLY=( $(compgen -W "stats lookup top search --db" -- "$cur") )
    return
  fi
  if [[ "$sub" == "cache" ]]; then
    COMPREPLY=( $(compgen -W "stats purge" -- "$cur") )
    return
  fi
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "` + strings.Join(flags, " ") + `" -- "$cur") )
  fi
}
complete -F _onyx_completions onyx
`)
}

func writeZshCompletion(b *strings.Builder, flags []string) {
	fmt.Fprintf(b, "#compdef onyx\n# zsh completion for onyx (generated by 'onyx completion zsh')\n")
	fmt.Fprintf(b, "_onyx() {\n")
	fmt.Fprintf(b, "  local -a subcmds\n")
	fmt.Fprintf(b, "  subcmds=(%s)\n", strings.Join(quoteWords(onyxSubcommands), " "))
	fmt.Fprintf(b, `  if (( CURRENT == 2 )); then
    _describe -t commands 'onyx command' subcmds
    return
  fi
  case "$words[2]" in
    db)
      _values 'db command' %s
      ;;
    cache)
      _values 'cache command' %s
      ;;
    scan)
      local -a flags
      flags=(%s)
      if [[ "$words[CURRENT]" == -* ]]; then
        _describe -t flags 'flag' flags
      else
        _hosts
      fi
      ;;
  esac
}
compdef _onyx onyx
`, strings.Join(quoteWords(dbSubcommands), " "), strings.Join(quoteWords(cacheSubcommands), " "), strings.Join(quoteWords(flags), " "))
}

func writeFishCompletion(b *strings.Builder, flags []string) {
	fmt.Fprintf(b, "# fish completion for onyx (generated by 'onyx completion fish')\n")
	for _, c := range onyxSubcommands {
		fmt.Fprintf(b, "complete -c onyx -n '__fish_use_subcommand' -a '%s'\n", c)
	}
	for _, s := range dbSubcommands {
		fmt.Fprintf(b, "complete -c onyx -n '__fish_seen_subcommand_from db' -a '%s'\n", s)
	}
	for _, s := range cacheSubcommands {
		fmt.Fprintf(b, "complete -c onyx -n '__fish_seen_subcommand_from cache' -a '%s'\n", s)
	}
	for _, f := range flags {
		if strings.HasPrefix(f, "--") {
			fmt.Fprintf(b, "complete -c onyx -l '%s'\n", strings.TrimLeft(f, "-"))
		} else {
			fmt.Fprintf(b, "complete -c onyx -s '%s'\n", strings.TrimLeft(f, "-"))
		}
	}
}

// quoteWords renders words as quoted strings for zsh array literals.
func quoteWords(words []string) []string {
	out := make([]string, len(words))
	for i, w := range words {
		out[i] = "'" + w + "'"
	}
	return out
}
