package dbupdate

import (
	"os"
	"path/filepath"
	"testing"
)

func TestSignAndVerifyRoundTrip(t *testing.T) {
	dir := t.TempDir()
	pubPath, secPath, err := GenerateKeypair(dir, "test key <test@example.test>")
	if err != nil {
		t.Fatal(err)
	}
	data := filepath.Join(dir, "feed.json.gz")
	if wErr := os.WriteFile(data, []byte("pretend feed bytes"), 0o644); wErr != nil {
		t.Fatal(wErr)
	}

	sigPath, err := Sign(secPath, data)
	if err != nil {
		t.Fatal(err)
	}
	if want := "feed.json.gz.minisig"; filepath.Base(sigPath) != want {
		t.Fatalf("sig path = %s, want *%s", sigPath, want)
	}
	if err := VerifyMinisign(pubPath, sigPath, data); err != nil {
		t.Fatalf("valid signature rejected: %v", err)
	}

	// Tampered data must fail.
	if wErr := os.WriteFile(data, []byte("tampered feed bytes"), 0o644); wErr != nil {
		t.Fatal(wErr)
	}
	if err := VerifyMinisign(pubPath, sigPath, data); err == nil {
		t.Fatal("tampered data accepted")
	}

	// A signature generated by GenerateTestKeypair (same format) verifies
	// against a GenerateKeypair public key only when keys match — cross-key
	// verification must fail.
	otherPub, otherSec := "", ""
	otherPub, otherSec = func() (a, b string) { return GenerateTestKeypair(t, dir) }()
	_ = otherPub
	sig2, sErr := Sign(otherSec, data)
	if sErr != nil {
		t.Fatal(sErr)
	}
	if err := VerifyMinisign(pubPath, sig2, data); err == nil {
		t.Fatal("cross-key signature accepted")
	}
}

func TestGenerateKeypairFileModes(t *testing.T) {
	dir := t.TempDir()
	pubPath, secPath, err := GenerateKeypair(dir, "")
	if err != nil {
		t.Fatal(err)
	}
	for path, want := range map[string]os.FileMode{pubPath: 0o644, secPath: 0o600} {
		fi, statErr := os.Stat(path)
		if statErr != nil {
			t.Fatal(statErr)
		}
		if fi.Mode().Perm() != want {
			t.Errorf("%s mode = %v, want %v", path, fi.Mode().Perm(), want)
		}
	}
}
