// Package pocgen generates target-specific PoCs by reading the original
// PoC from Boreas37/CVE-PoC-Tracker (via pocs.FetchRawPoC) and asking an
// LLM to adapt it to the scanned target's fingerprint.
//
// It is off by default and requires --poc-generate plus --force (targets
// you own). Generated PoCs are written to disk for manual review, never
// auto-executed. All target-controlled strings are sanitized before they
// reach the prompt.
package pocgen

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/Boreas37/onyx/internal/llm"
	"github.com/Boreas37/onyx/internal/pocs"
	"github.com/Boreas37/onyx/internal/sanitize"
	"github.com/Boreas37/onyx/internal/scanner"
)

// Generated is an alias for scanner.GeneratedPoC so pocgen and the
// scanner share the same wire type without a circular import cycle.
type Generated = scanner.GeneratedPoC

// Options tunes generation.
type Options struct {
	Provider   string // openai|ollama|anthropic
	Model      string
	APIKey     string
	Endpoint   string
	OutputDir  string // default ./pocs
	TrackerDir string // pocs dir, default ~/projects/cve-tracker
}

// TargetCtx is the sanitized fingerprint passed to the LLM prompt.
type TargetCtx struct {
	Target           string
	WordPressVersion string
	ContentDir       string
	PluginsDir       string
	Interesting      []string
	WAF              string
	AuthStatus       string
	Detected         []scanner.Detected
}

// BuildTargetCtx builds a sanitized TargetCtx from a scan Result and the
// scanner's content/plugin dirs.
func BuildTargetCtx(res *scanner.Result, contentDir, pluginsDir string) TargetCtx {
	tc := TargetCtx{
		Target:           sanitize.Text(res.Target, 300),
		WordPressVersion: sanitize.Text(res.WordPressVersion, 64),
		ContentDir:       sanitize.Text(contentDir, 64),
		PluginsDir:       sanitize.Text(pluginsDir, 128),
		AuthStatus:       sanitize.Text(res.AuthStatus, 32),
	}
	for _, s := range res.Interesting {
		tc.Interesting = append(tc.Interesting, sanitize.Text(s, 300))
		if strings.Contains(strings.ToLower(s), "waf") || strings.Contains(strings.ToLower(s), "challenge") {
			tc.WAF = sanitize.Text(s, 300)
		}
	}
	for _, d := range res.Detected {
		tc.Detected = append(tc.Detected, scanner.Detected{
			Slug:    sanitize.Text(d.Slug, 200),
			Type:    sanitize.Text(d.Type, 32),
			Version: sanitize.Text(d.Version, 64),
			Source:  sanitize.Text(d.Source, 32),
		})
	}
	return tc
}

// systemPrompt is the fixed system instruction for PoC adaptation.
const systemPrompt = `You are a security researcher helping an authorized tester adapt a public WordPress PoC to their own lab target.

Rules:
- Only adapt the existing PoC to the target's paths/versions/headers. Do not invent a new vulnerability.
- Use the provided TargetCtx (base URL, contentDir, pluginsDir, installed versions, WAF hint) to adjust URLs, payloads and headers.
- Output a single self-contained Python 3 script (requests library) that prints "[VULN]" on success and "[SAFE]" otherwise. No extra prose outside the script.
- Add a header comment: "# Generated by onyx pocgen for authorized testing only — do not run against targets you do not own".
- If the original PoC is empty or irrelevant, output a minimal checker that GETs the target's readme/style.css version and reports mismatch.
- Sanitize all inputs; do not output raw target HTML.`

// userPrompt builds the user message from TargetCtx, Vuln and RawPoC.
func userPrompt(tc TargetCtx, vuln scanner.Vulnerability, slug, typ, version, rawPoC string) string {
	var b strings.Builder
	b.WriteString("TargetCtx:\n")
	b.WriteString(fmt.Sprintf("- Target: %s\n", tc.Target))
	b.WriteString(fmt.Sprintf("- WordPress: %s\n", tc.WordPressVersion))
	b.WriteString(fmt.Sprintf("- contentDir: %s\n", tc.ContentDir))
	b.WriteString(fmt.Sprintf("- pluginsDir: %s\n", tc.PluginsDir))
	b.WriteString(fmt.Sprintf("- WAF: %s\n", tc.WAF))
	b.WriteString(fmt.Sprintf("- AuthStatus: %s\n", tc.AuthStatus))
	b.WriteString(fmt.Sprintf("- Component: %s/%s@%s\n", typ, slug, version))
	if len(tc.Interesting) > 0 {
		b.WriteString("- Interesting: " + strings.Join(tc.Interesting, "; ") + "\n")
	}
	b.WriteString("\nVuln:\n")
	b.WriteString(fmt.Sprintf("- ID: %s\n", sanitize.Text(vuln.ID, 200)))
	b.WriteString(fmt.Sprintf("- CVE: %s\n", sanitize.Text(vuln.CVE, 64)))
	b.WriteString(fmt.Sprintf("- Title: %s\n", sanitize.Text(vuln.Title, 500)))
	b.WriteString(fmt.Sprintf("- Rating: %s\n", sanitize.Text(vuln.Rating, 32)))
	b.WriteString(fmt.Sprintf("- Affected: %s\n", strings.Join(vuln.AffectedLabels, ", ")))
	b.WriteString("\nRaw PoC (first 6000 chars, truncated):\n")
	raw := rawPoC
	if len(raw) > 6000 {
		raw = raw[:6000] + "\n...[truncated]"
	}
	if strings.TrimSpace(raw) == "" {
		raw = "(empty — generate a version checker)"
	}
	b.WriteString("```\n" + raw + "\n```\n")
	b.WriteString("\nAdapt the PoC to TargetCtx. Output ONLY the Python script.\n")
	return b.String()
}

// pocCacheEntry holds the cached raw PoC and its source URL.
type pocCacheEntry struct {
	Raw string
	URL string
}

// GenerateForFinding generates one PoC per CVE of a finding, using the top
// PoC link for each CVE. It writes files to opts.OutputDir and returns the
// Generated entries. The first LLM failure is returned as a warning (not a
// hard error) so the scan still reports partial results.
func GenerateForFinding(ctx context.Context, provider llm.Provider, tc TargetCtx, f scanner.Finding, opts Options, rawCache map[string]pocCacheEntry) ([]Generated, []string) {
	var out []Generated
	var warns []string
	if opts.OutputDir == "" {
		opts.OutputDir = "./pocs"
	}
	// Ensure output dir exists (0700).
	if err := os.MkdirAll(opts.OutputDir, 0o700); err != nil {
		warns = append(warns, fmt.Sprintf("poc output dir: %v", err))
		return nil, warns
	}
	for _, vuln := range f.Vulnerabilities {
		cve := strings.TrimSpace(vuln.CVE)
		if cve == "" {
			continue
		}
		// Resolve PoC link: top 1 from tracker. If none, still generate a checker.
		var pocURL, raw string
		if cached, ok := rawCache[cve]; ok {
			raw = cached.Raw
			pocURL = cached.URL
		} else {
			// Try to fetch from tracker dir if set, else leave raw empty.
			if opts.TrackerDir != "" {
				links := pocs.ExtractLinks(opts.TrackerDir, cve)
				if len(links) > 0 {
					// Pick highest stars, fetch raw.
					top := pocs.TopByStars(func() []pocs.PoCLink {
						f := pocs.NewFetcher("")
						return f.Fetch(links)
					}())
					if len(top) > 0 {
						pocURL = top[0].URL
						// Fetch with a short sub-context so one slow repo does not block others.
						subCtx, cancel := context.WithTimeout(ctx, 15*time.Second)
						if body, err := pocs.FetchRawPoC(subCtx, pocURL); err == nil {
							raw = body
						} else {
							warns = append(warns, fmt.Sprintf("%s raw PoC fetch: %v", cve, err))
						}
						cancel()
					}
				}
			}
		}
		// If raw still empty, Generate will produce a checker.
		sysP := systemPrompt
		userP := userPrompt(tc, vuln, f.Slug, f.Type, f.InstalledVersion, raw)
		script, err := provider.Generate(ctx, sysP, userP)
		if err != nil {
			warns = append(warns, fmt.Sprintf("%s llm: %v", cve, err))
			continue
		}
		// Sanitize filename: slug-cve.py
		safeSlug := sanitize.Text(f.Slug, 100)
		safeSlug = strings.ReplaceAll(safeSlug, "/", "_")
		safeCVE := sanitize.Text(cve, 64)
		fname := fmt.Sprintf("%s-%s.py", safeSlug, safeCVE)
		if safeCVE == "" {
			fname = fmt.Sprintf("%s-%s.py", safeSlug, sanitize.Text(vuln.ID, 64))
		}
		path := filepath.Join(opts.OutputDir, fname)
		// Write 0600, header already in script but ensure file is not world-readable.
		if err := os.WriteFile(path, []byte(script+"\n"), 0o600); err != nil {
			warns = append(warns, fmt.Sprintf("%s write: %v", cve, err))
			continue
		}
		out = append(out, Generated{
			CVE:       cve,
			Slug:      f.Slug,
			Type:      f.Type,
			Version:   f.InstalledVersion,
			SourceURL: pocURL,
			Output:    path,
		})
	}
	return out, warns
}

// Generate generates PoCs for every finding in res, reusing a single LLM
// provider and a raw PoC cache keyed by CVE.
func Generate(ctx context.Context, res *scanner.Result, tc TargetCtx, provider llm.Provider, opts Options) ([]Generated, []string) {
	var all []Generated
	var warns []string
	rawCache := make(map[string]pocCacheEntry)
	// Pre-warm raw cache for all CVEs in one pass.
	if opts.TrackerDir != "" {
		for i := range res.Findings {
			for _, v := range res.Findings[i].Vulnerabilities {
				cve := strings.TrimSpace(v.CVE)
				if cve == "" {
					continue
				}
				if _, ok := rawCache[cve]; ok {
					continue
				}
				links := pocs.ExtractLinks(opts.TrackerDir, cve)
				if len(links) == 0 {
					continue
				}
				top := pocs.TopByStars(pocs.NewFetcher("").Fetch(links))
				if len(top) == 0 {
					continue
				}
				subCtx, cancel := context.WithTimeout(ctx, 15*time.Second)
				if body, err := pocs.FetchRawPoC(subCtx, top[0].URL); err == nil && strings.TrimSpace(body) != "" {
					rawCache[cve] = pocCacheEntry{Raw: body, URL: top[0].URL}
				} else if body != "" {
					// Even empty raw but valid URL is worth caching for source_url.
					rawCache[cve] = pocCacheEntry{Raw: body, URL: top[0].URL}
				}
				cancel()
			}
		}
	}
	for _, f := range res.Findings {
		gen, w := GenerateForFinding(ctx, provider, tc, f, opts, rawCache)
		all = append(all, gen...)
		warns = append(warns, w...)
	}
	return all, warns
}
